name: Mock Deployment Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, review_requested, review_request_removed]
  pull_request_review:
    types: [submitted]

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    outputs:
      approved: ${{ steps.approval-check.outputs.approved }}
    steps:
      - name: Check PR approvals
        id: approval-check
        run: |
          approvals=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" | \
            jq '[.[] | select(.state == "APPROVED")] | length')
          echo "Number of approvals: $approvals"
          if [ "$approvals" -ge 2 ]; then
            echo "approved=true" >> $GITHUB_OUTPUT
            echo "✅ PR has required number of approvals (2)"
          else
            echo "approved=false" >> $GITHUB_OUTPUT
            echo "❌ PR needs at least 2 approvals (current: $approvals)"
          fi

  mock-deploy:
    needs: check-approvals
    if: needs.check-approvals.outputs.approved == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Mock Deployment
        run: |
          echo "🚀 Starting mock deployment process..."
          echo "📦 Pretending to package application"
          sleep 2
          echo "🔄 Simulating deployment to staging"
          sleep 2
          echo "✅ Mock deployment completed successfully!"
